### ISSUE TITLE
Angle units

### ISSUE THREAD

**Issue by chrisjbillington** [pacosalces/physunits#1]
Despite there being no SI unit of angle, [we all know](https://en.wikipedia.org/wiki/William_Daniel_Phillips) that if there was one it would be the radian.

I think it would make more sense for this package to define `deg = pi / 180` and e.g `mrad = 0.001` instead of `deg = 1` and `mrad = 0.057295779513082325`. As it is at the moment it's treating degrees as the preferred unit of angle which doesn't gel with numpy trig functions and things like that.

**Comment by pacosalces** [comment]
Thanks! I agree, and have updated the angle units accordingly!
