### ISSUE TITLE
keV not correct

### ISSUE THREAD

**Issue by chrisjbillington** [pacosalces/physunits#2]
`keV` is defined as `1000` instead of a multiple of `eV`:

```python
>>> import physunits
>>> physunits.eV
1.602176634e-19
>>> physunits.keV
1000.0
```

**Comment by pacosalces** [comment]
Add fix in commit `04fd62f`. Will test now.

**Comment by pacosalces** [comment]
I have tested across different environments from py3.7 to 3.9 and this seems to work fine. I have propagated the changes to the package so you can now run 

`python -m pip install physunits==1.0.1`

on your favorite local environment or alternatively

`sudo pacman -S python-physunits`

if it applies to your local Arch-based distribution and the issue should be fixed. Thanks for noting it in the first place and contributing to making this package better.

**Comment by chrisjbillington** [comment]
Thanks Paco!
