### ISSUE TITLE
Incorrect definition of Torr

### ISSUE THREAD

**Issue by chrisjbillington** [pacosalces/physunits#3]
physunits defines Torr as:
```python
Torr = 1 / (760*atm)
```
But it should be `atm / 760`

**Comment by pacosalces** [comment]
Shame on me. That should be fixed now, please verify.

**Comment by chrisjbillington** [comment]
Verified! Unfortunately, Bar and mBar are incorrect as well, should be 1e5 Pa and 1e5 mPa, not 1e-5.

**Comment by pacosalces** [comment]
Re-shame. Fixed as well, please verify! :dancing_men:

**Comment by chrisjbillington** [comment]
Thanks paco! Verified.
